
# Controls when the workflow will run
on:
  push:
    branches:  '*' 
  pull_request:
    branches:  '*' 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.5.4', '3.6.3', '3.8.5' ]

    name: Maven ${{ matrix.maven }} sample

    steps:

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v2.6.0
        with:
          java-version: 8
          maven-version: ${{ matrix.maven }}

      - run: mvn -V
      
